spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:./.env.prod[.properties]

  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_PG_USERNAME}
    password: ${POSTGRES_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

logging:
  level:
    com.yourcompany.userprofile: INFO
  file:
    name: /var/log/user-profile-service/application.log