spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:./.env.dev[.properties]

  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://user-profile-postgres:5432/user_profile}
    username: ${POSTGRES_PG_USERNAME:user-profile}
    password: ${POSTGRES_PG_PASSWORD:user-profile}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:user-profile-service}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}

logging:
  level:
    com.yourcompany.userprofile: DEBUG
    org.springframework.web: DEBUG