spring:
  application:
    name: messaging-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:5000ms}
  cache:
    type: redis

messaging:
  websocket:
    endpoint: /ws/messaging
    allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:*,http://127.0.0.1:*}
    broker:
      enable: true
      prefix: /topic
      app-prefix: /app
    sockjs:
      enabled: true

server:
  port: ${MESSAGING_SERVICE_PORT:8085}
  servlet:
    context-path: /api/messaging

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${MESSAGING_EUREKA_INSTANCE_HOSTNAME:messaging-service}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.cs.vsu.social_network.messaging_service: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: ${server.servlet.context-path}/api-docs/swagger-config
    url: ${server.servlet.context-path}/api-docs
    operations-sorter: method
    tags-sorter: alpha

app:
  gateway:
    signature-secret: ${SIGNATURE_KEY_SECRET:dev-shared-signature-secret}


kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    group-id: messaging-service-group
    auto-offset-reset: earliest
    enable-auto-commit: false
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
