spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:./.env.prod[.properties]
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_PG_USERNAME}
    password: ${POSTGRES_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${UPLOAD_SERVICE_PORT:8084}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:upload-service}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

logging:
  level:
    ru.cs.vsu.social_network.upload_service: INFO
  file:
    name: /var/log/upload-service/application.log

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  public-url: ${MINIO_PUBLIC_URL}
  secure: ${MINIO_SECURE:true}

